### ISSUE TITLE
line split brokes documentation

### ISSUE THREAD

**Issue by tondahermankovi** [simgunz/doxymatlab#4]
when splitting a long line in properties part of the code using three dots for example like this

> properties(Constant, Hidden)
		ConfigPropList = {'prop1','prop2' ,... 
             'prop3','prop4'};
	end % properties
[Detector.txt](https://github.com/simgunz/doxymatlab/files/652088/Detector.txt)

the documentation for this class is not generated. see the attached file.

**Comment by tondahermankovi** [comment]
can anyone confirm described behaviour ? Or is the project completely dead?

**Comment by simgunz** [comment]
I still haven't had the time to look into this issue. Probably the code needs a modification to parse the three dots and understand it is a line break.

**Comment by tondahermankovi** [comment]
any improvements ?

**Comment by simgunz** [comment]
This should be fixed now. But please test if it's working and not breaking other things, and give me a feedback on the results.

**Comment by tondahermankovi** [comment]
I confirm. the issue is fixed. Thanks
