### ISSUE TITLE
Removing anonymous_namespace

### ISSUE THREAD

**Issue by bytecrook** [simgunz/doxymatlab#9]
Hello! First off, thanks for taking over this script. I'm finding it very useful in documenting my ever increasingly complicated MATLAB classes.

I have a quick question: when documenting code with namespaces, the code appends anonymous_namespace to classes in the base directory (i.e. not in a separate folder)

For example, for the following file structure:

/msource
../someClass.m
../+newNamespace/newClass.m

The class list looks like:

![capture](https://user-images.githubusercontent.com/22480994/29847265-f6b79938-8cd7-11e7-8a16-bd090de9bf14.JPG)

I was wondering if there was a way to remove the 'anonymous_function' label from the list? Could this namespace be replaced by something like the project name or, better yet, raised up a level. Ideally the output will look something like (please excuse the poor Paint job):

![capture2](https://user-images.githubusercontent.com/22480994/29847338-6e792fcc-8cd8-11e7-8a75-e06536a89d2f.jpg)

**Comment by bytecrook** [comment]
I figured out a solution for this. In m2cpp.pl, replace the line starting with:
`$output = "namespace $namespace {\n";`

with this if/else statement:
```
if ($namespace eq "")
{
    $output = '';
	}
else{
	$output = "namespace $namespace {\n";
}
```

This removes the `anonymous_namespace` tags and the classes in the base directory will be displayed like the example I had in the post above.

**Comment by kvid** [comment]
Just a reminder: to avoid the risk of a dangling curly bracket with the code change above, the `$output=$output."};\n};\n";` line near the end of m2cpp.pl should also be replaced with something like this:
```
$output=$output."};\n";
if ($namespace ne "") {
  $output=$output."};\n";
}
```

**Comment by simgunz** [comment]
That seems a good solution, if you send me a pull request I'll merge it right away or I'll implement the changes as soon as I have time.
